// / FIREBASE AUTH ACTIONS
export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
export const LOGIN_WITH_PROVIDER_FIREBASE_SUCCESS = 'LOGIN_WITH_PROVIDER_FIREBASE_SUCCESS';
export const LOGIN_WITH_PROVIDER_FIREBASE_FAILURE = 'LOGIN_WITH_PROVIDER_FIREBASE_FAILURE';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const FETCH_FIREBASE_USER_SUCCESS = 'FETCH_FIREBASE_USER_SUCCESS';
export const FETCH_FIREBASE_USER_FAILURE = 'FETCH_FIREBASE_USER_FAILURE';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_INFO_SUCCESS = 'SET_USER_INFO_SUCCESS';
export const SET_USER_INFO_FAILURE = 'SET_USER_INFO_FAILURE';

// DEEP WORK
export const UPDATE_WORK_DATE = 'UPDATE_WORK_DATE';
export const UPDATE_TIME_FORMAT = 'UPDATE_TIME_FORMAT';
export const CHART_VIEW = 'CHART_VIEW';
export const OPEN_WORK_HOVER = 'OPEN_WORK_HOVER';
export const CLOSE_WORK_HOVER = 'CLOSE_WORK_HOVER';
export const WORK_HOUR_RANGE = 'WORK_HOUR_RANGE';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const ADD_DAY = 'ADD_DAY';
export const SUBTRACT_DAY = 'SUBTRACT_DAY';

