// / FIREBASE AUTH ACTIONS
export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';

// DEEP WORK
export const UPDATE_DAY = 'UPDATE_DAY';
export const TIME_FORMAT = 'TIME_FORMAT';
export const CHART_VIEW = 'CHART_VIEW';
